version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: inch_ex
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: dialyxir
    versions:
    - 1.0.0
