language: elixir
elixir:
  - 1.3.1
otp_release:
  - 19.0
sudo: false
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
before_script:
  - mkdir /tmp/slapd
  - slapd -f .travis/ldap/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=test,dc=com -w test -f .travis/ldap/base.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=test,dc=com -w test -f .travis/ldap/test_data.ldif
after_script:
  - mix inch.report
